apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend
  labels:
    app: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
      - name: backend
        image: mohamedessam1911/project-backend:latest
        env:
        - name: MYSQL_HOST
          value: "project-mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "projectdb"
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
      - name: frontend
        image: mohamedessam1911/project-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-mysql
  template:
    metadata:
      labels:
        app: project-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306

