apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: project-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: project-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31002
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: project-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None

